#!/usr/bin/env python3
"""Align local-variable names of a freshly built project with a reference export.

usage: align_locals.py REFERENCE_EXPORT_DIR FRESH_EXPORT_DIR OUT.json
Both directories are ExportManatee.java outputs. For every function, the decompiled C of both
is tokenised and aligned; generic names in the fresh build (uVar1, puVar2 ...) that line up with
a meaningful name in the reference become name-keyed "locals" entries. Used once to make
`build_project.sh` reproduce the reference project's local names.
"""
import difflib, glob, json, os, re, sys

GENERIC = re.compile(r'^([a-z]{1,2}[A-Z]?[a-zA-Z]*Var\d+|local_[0-9a-f_]+|extraout_\w+|temp_\w+|in_\w+|unaff_\w+)$')
TOK = re.compile(r'[A-Za-z_]\w*|0x[0-9a-fA-F]+|\d+|\S')

def body(path):
    t = open(path).read()
    i = t.find('/* ---- decompiled ---- */')
    return TOK.findall(t[i:]) if i >= 0 else []

def main():
    ref, fresh, out = sys.argv[1:4]
    funcs = []
    for fp in sorted(glob.glob(os.path.join(fresh, 'functions', '*.txt'))):
        rp = os.path.join(ref, 'functions', os.path.basename(fp))
        if not os.path.exists(rp):
            continue
        a, b = body(rp), body(fp)
        pairs = {}
        for op, i1, i2, j1, j2 in difflib.SequenceMatcher(None, a, b, autojunk=False).get_opcodes():
            if op == 'replace' and i2 - i1 == j2 - j1:
                for x, y in zip(a[i1:i2], b[j1:j2]):
                    if GENERIC.match(y) and re.match(r'^[A-Za-z_]\w*$', x) and not GENERIC.match(x):
                        pairs.setdefault(y, set()).add(x)
        locals_ = {k: next(iter(v)) for k, v in pairs.items() if len(v) == 1}
        if locals_:
            funcs.append({'addr': '0x' + os.path.basename(fp).split('_')[0].lstrip('0'), 'locals': locals_})
    json.dump({'_comment': 'Generated by tools/ghidra/align_locals.py: fresh-build decompiler names -> reference names.',
               'functions': funcs}, open(out, 'w'), indent=1)
    print(f'{sum(len(f["locals"]) for f in funcs)} names in {len(funcs)} functions -> {out}')

if __name__ == '__main__':
    main()
