// Snapshot every non-default decompiler local name (and non-default type) of every function into an
// annotation file, keyed by stable storage keys, so a fresh project build reproduces them.
// Usage (GUI via GhidraMCP or headless): arg 1 = output JSON path.
// @category Manatee
import ghidra.app.script.GhidraScript;
import ghidra.app.decompiler.*;
import ghidra.program.model.listing.*;
import ghidra.program.model.pcode.*;
import ghidra.program.model.data.*;
import com.google.gson.*;
import java.io.*;
import java.util.*;
import java.util.regex.Pattern;

public class HarvestLocals extends GhidraScript {
    private static final Pattern DEFAULT = Pattern.compile(
        "^([a-z]{1,2}[A-Z]?[a-zA-Z]*Var\\d+|local_[0-9a-f_]+|in_\\w+|unaff_\\w+|extraout_\\w+|temp_\\w+|param_\\d+|stack\\w*)$");

    static String key(HighSymbol hs) {
        try {
            VariableStorage st = hs.getStorage();
            if (st == null || st.getVarnodes().length == 0) return null;
            if (st.isRegisterStorage() && st.getRegister() != null)
                return "@" + st.getRegister().getName() + ":" +
                    (hs.getPCAddress() == null ? "?" : "0x" + Long.toHexString(hs.getPCAddress().getOffset()));
            if (st.isStackStorage()) return "@stack:" + st.getStackOffset();
            Varnode vn = st.getFirstVarnode();
            return "@" + vn.getAddress().getAddressSpace().getName() + ":" + Long.toHexString(vn.getOffset()) +
                (hs.getPCAddress() == null ? "" : ":0x" + Long.toHexString(hs.getPCAddress().getOffset()));
        } catch (Exception e) { return null; }
    }

    @Override
    public void run() throws Exception {
        DecompInterface di = new DecompInterface();
        DecompileOptions opts = new DecompileOptions();
        opts.grabFromProgram(currentProgram);
        di.setOptions(opts);
        di.openProgram(currentProgram);
        JsonArray funcs = new JsonArray();
        int n = 0;
        for (Function f : currentProgram.getFunctionManager().getFunctions(true)) {
            DecompileResults r = di.decompileFunction(f, 60, monitor);
            if (r == null || r.getHighFunction() == null) continue;
            JsonObject locals = new JsonObject();
            Iterator<HighSymbol> it = r.getHighFunction().getLocalSymbolMap().getSymbols();
            while (it.hasNext()) {
                HighSymbol hs = it.next();
                if (hs.isParameter() || DEFAULT.matcher(hs.getName()).matches()) continue;
                String k = key(hs);
                if (k == null || k.contains("?") || locals.has(k)) continue;
                DataType dt = hs.getDataType();
                if (dt != null && !(dt instanceof Undefined) && !dt.getName().startsWith("undefined")) {
                    JsonObject v = new JsonObject();
                    v.addProperty("name", hs.getName());
                    v.addProperty("type", dt.getDisplayName());
                    locals.add(k, v);
                } else {
                    locals.addProperty(k, hs.getName());
                }
                n++;
            }
            if (locals.size() == 0) continue;
            JsonObject e = new JsonObject();
            e.addProperty("addr", "0x" + Long.toHexString(f.getEntryPoint().getOffset()));
            e.add("locals", locals);
            funcs.add(e);
        }
        di.dispose();
        JsonObject root = new JsonObject();
        root.addProperty("_comment", "Generated by HarvestLocals.java from the reference project: decompiler local names keyed by storage. Re-generate after renaming locals in Ghidra.");
        root.add("functions", funcs);
        try (Writer w = new FileWriter(getScriptArgs()[0])) {
            new GsonBuilder().setPrettyPrinting().create().toJson(root, w);
        }
        println("harvested " + n + " locals in " + funcs.size() + " functions");
    }
}
